language: python

cache: pip

python:
  - "3.7"

install:
  - make travis-install

jobs:
  include:
    - stage: unit-test
      script:
        - make travis-unit
        - make travis-examples
        - make travis-doc
        - make travis-end
